module.exports = {
  docs: [
    "index",
    "commandline",
    "vi",
    "git",
    "docker",
    "shell-scripting",
    "regex",
    {
      type: "category",
      label: "Misc",
      collapsed: true,
      link: {
        type: "generated-index",
      },
      items: [
        "setup",
        "administration",
        "pgp",
        "gnuplot",
        "filesystem",
        "network-setup",
        "firewall",
        "network-security",
        "tls-key-management",
        "storage-management",
        "apache",
        "nextcloud",
        "selinux",
        "jenkins",
        "hpc",
        "module",
        "brew",
        "privacy",
        "latex",
        "wsl",
        "more-tips-tricks",
      ],
    },
    "resources",
    "license",
  ],
};
